### ISSUE TITLE
Add support for Visual Studio 2017 for Mac

### ISSUE THREAD

**Issue by boydj** [smichelotti/AzureEnvironmentSelector#3]
Any chance of supporting VS 2017 for Mac?

**Comment by smichelotti** [comment]
Not currently in our pipeline. Question: are you able to get VS to work for Azure Government using the AadProvider.Configuration.json as documented [here](https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-get-started-connect-with-vs) in the section called `Manually configuring your target`?
