### ISSUE TITLE
Add support for Visual Studio 2019

### ISSUE THREAD

**Issue by redshiftz** [smichelotti/AzureEnvironmentSelector#4]
Will Visual Studio 2019 be supported? 
Also, the manual how-to link (https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-get-started-connect-with-vs) has been taken down so we can't even find out how to do this without your extension.

**Comment by smichelotti** [comment]
The extension is not needed with VS 2019 because VS 2019 now supports this functionality natively. We are considering adding a couple of bullet points to our docs to show how to do this (using the built-in VS 2019 functionality).

**Comment by EntityAdam** [comment]
Hey Steve, can confirm that this is not working correctly in VS2019 (out of the box). There is 0 documentation, so I had no option but to add VS2019 support to the extension which worked for now. Looking forward to the documentation.

**Comment by smichelotti** [comment]
Just adding the link here to the documentation for future readers: https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-connect-vs
